/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppFlowFlowIdRouteImport } from './routes/app/flow.$flowId'
import { Route as ApiWebhookFlowIdRouteImport } from './routes/api/webhook/$flowId'
import { Route as ApiWebhookSplatRouteImport } from './routes/api/webhook/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppSettingsTeamIndexRouteImport } from './routes/app/settings/team/index'
import { Route as AppSettingsBillingIndexRouteImport } from './routes/app/settings/billing/index'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/app/settings/',
  path: '/app/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFlowFlowIdRoute = AppFlowFlowIdRouteImport.update({
  id: '/app/flow/$flowId',
  path: '/app/flow/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookFlowIdRoute = ApiWebhookFlowIdRouteImport.update({
  id: '/api/webhook/$flowId',
  path: '/api/webhook/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookSplatRoute = ApiWebhookSplatRouteImport.update({
  id: '/api/webhook/$',
  path: '/api/webhook/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsTeamIndexRoute = AppSettingsTeamIndexRouteImport.update({
  id: '/app/settings/team/',
  path: '/app/settings/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsBillingIndexRoute = AppSettingsBillingIndexRouteImport.update({
  id: '/app/settings/billing/',
  path: '/app/settings/billing/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/rpc/$': typeof RpcSplatRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/api/webhook/$flowId': typeof ApiWebhookFlowIdRoute
  '/app/flow/$flowId': typeof AppFlowFlowIdRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/billing': typeof AppSettingsBillingIndexRoute
  '/app/settings/team': typeof AppSettingsTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/rpc/$': typeof RpcSplatRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/api/webhook/$flowId': typeof ApiWebhookFlowIdRoute
  '/app/flow/$flowId': typeof AppFlowFlowIdRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/billing': typeof AppSettingsBillingIndexRoute
  '/app/settings/team': typeof AppSettingsTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/rpc/$': typeof RpcSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/api/webhook/$flowId': typeof ApiWebhookFlowIdRoute
  '/app/flow/$flowId': typeof AppFlowFlowIdRoute
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/settings/billing/': typeof AppSettingsBillingIndexRoute
  '/app/settings/team/': typeof AppSettingsTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/rpc/$'
    | '/app'
    | '/api/auth/$'
    | '/api/webhook/$'
    | '/api/webhook/$flowId'
    | '/app/flow/$flowId'
    | '/app/settings'
    | '/app/settings/billing'
    | '/app/settings/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/rpc/$'
    | '/app'
    | '/api/auth/$'
    | '/api/webhook/$'
    | '/api/webhook/$flowId'
    | '/app/flow/$flowId'
    | '/app/settings'
    | '/app/settings/billing'
    | '/app/settings/team'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/rpc/$'
    | '/app/'
    | '/api/auth/$'
    | '/api/webhook/$'
    | '/api/webhook/$flowId'
    | '/app/flow/$flowId'
    | '/app/settings/'
    | '/app/settings/billing/'
    | '/app/settings/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  RpcSplatRoute: typeof RpcSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhookSplatRoute: typeof ApiWebhookSplatRoute
  ApiWebhookFlowIdRoute: typeof ApiWebhookFlowIdRoute
  AppFlowFlowIdRoute: typeof AppFlowFlowIdRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppSettingsBillingIndexRoute: typeof AppSettingsBillingIndexRoute
  AppSettingsTeamIndexRoute: typeof AppSettingsTeamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/flow/$flowId': {
      id: '/app/flow/$flowId'
      path: '/app/flow/$flowId'
      fullPath: '/app/flow/$flowId'
      preLoaderRoute: typeof AppFlowFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/$flowId': {
      id: '/api/webhook/$flowId'
      path: '/api/webhook/$flowId'
      fullPath: '/api/webhook/$flowId'
      preLoaderRoute: typeof ApiWebhookFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/$': {
      id: '/api/webhook/$'
      path: '/api/webhook/$'
      fullPath: '/api/webhook/$'
      preLoaderRoute: typeof ApiWebhookSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/team/': {
      id: '/app/settings/team/'
      path: '/app/settings/team'
      fullPath: '/app/settings/team'
      preLoaderRoute: typeof AppSettingsTeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/billing/': {
      id: '/app/settings/billing/'
      path: '/app/settings/billing'
      fullPath: '/app/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  RpcSplatRoute: RpcSplatRoute,
  AppIndexRoute: AppIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhookSplatRoute: ApiWebhookSplatRoute,
  ApiWebhookFlowIdRoute: ApiWebhookFlowIdRoute,
  AppFlowFlowIdRoute: AppFlowFlowIdRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppSettingsBillingIndexRoute: AppSettingsBillingIndexRoute,
  AppSettingsTeamIndexRoute: AppSettingsTeamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
