/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as FlowFlowIdRouteImport } from './routes/flow.$flowId'
import { Route as ApiWebhookFlowIdRouteImport } from './routes/api/webhook/$flowId'
import { Route as ApiWebhookSplatRouteImport } from './routes/api/webhook/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FlowFlowIdRoute = FlowFlowIdRouteImport.update({
  id: '/flow/$flowId',
  path: '/flow/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookFlowIdRoute = ApiWebhookFlowIdRouteImport.update({
  id: '/api/webhook/$flowId',
  path: '/api/webhook/$flowId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookSplatRoute = ApiWebhookSplatRouteImport.update({
  id: '/api/webhook/$',
  path: '/api/webhook/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/api/webhook/$flowId': typeof ApiWebhookFlowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/api/webhook/$flowId': typeof ApiWebhookFlowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/flow/$flowId': typeof FlowFlowIdRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/webhook/$': typeof ApiWebhookSplatRoute
  '/api/webhook/$flowId': typeof ApiWebhookFlowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/flow/$flowId'
    | '/rpc/$'
    | '/api/auth/$'
    | '/api/webhook/$'
    | '/api/webhook/$flowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/flow/$flowId'
    | '/rpc/$'
    | '/api/auth/$'
    | '/api/webhook/$'
    | '/api/webhook/$flowId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/setup'
    | '/flow/$flowId'
    | '/rpc/$'
    | '/api/auth/$'
    | '/api/webhook/$'
    | '/api/webhook/$flowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  FlowFlowIdRoute: typeof FlowFlowIdRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWebhookSplatRoute: typeof ApiWebhookSplatRoute
  ApiWebhookFlowIdRoute: typeof ApiWebhookFlowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flow/$flowId': {
      id: '/flow/$flowId'
      path: '/flow/$flowId'
      fullPath: '/flow/$flowId'
      preLoaderRoute: typeof FlowFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/$flowId': {
      id: '/api/webhook/$flowId'
      path: '/api/webhook/$flowId'
      fullPath: '/api/webhook/$flowId'
      preLoaderRoute: typeof ApiWebhookFlowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/$': {
      id: '/api/webhook/$'
      path: '/api/webhook/$'
      fullPath: '/api/webhook/$'
      preLoaderRoute: typeof ApiWebhookSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  FlowFlowIdRoute: FlowFlowIdRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWebhookSplatRoute: ApiWebhookSplatRoute,
  ApiWebhookFlowIdRoute: ApiWebhookFlowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
